### ISSUE TITLE
Scripts/SQLs placed under docker-entrypoint-initdb.d are not running

### ISSUE THREAD

**Issue by unsafePtr** [dbsystel/postgresql-partman-container#19]
Thank you for your work! Might be an issue, or I am doing something wrong.

I am using docker compose and wanted to use image directly. However sceipts/SQLs placed under docker-entrypoint-initdb.d are not run

```yml
version: "3.8"
name: infra
services:
  db:
    image: ghcr.io/dbsystel/postgresql-partman:16-4 # postgre with pg_partman extension for partitioning https://github.com/dbsystel/postgresql-partman-container
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: MyDb
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network  
  
volumes:
  local_pgdata:
  scripts:
      
networks:
  postgres-network:
    driver: bridge
 ```
 
 Scripts folder contains a simple script (1_users.sql)
 ```sql
 ALTER ROLE "admin123" SUPERUSER;
```
 
 I've cleaned volume before running docker-compose, so setup is clean
 
![Screenshot 2024-09-10 223039](https://github.com/user-attachments/assets/2acfa1b2-dcd0-460a-b4b8-563b4a82ae72)
